apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  labels:
    app: angular-app
spec:
  replicas: 1  # Number of instances of your Angular app to run
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app
          image: gbsartifactory.edst.ibm.com/test_docker/angular-example:${BUILD_NUMBER}  # Replace with your Docker image
      imagePullSecrets:
        - name: artifactory-angular
        ports:
        - containerPort: 80
